# Generated by Django 5.2.8 on 2025-11-27 21:40

import clinicas.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', clinicas.models.UpperCharField(max_length=64, unique=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('logradouro', clinicas.models.UpperCharField(blank=True, max_length=64, null=True)),
                ('complemento', clinicas.models.UpperCharField(blank=True, max_length=32, null=True)),
                ('bairro', clinicas.models.UpperCharField(blank=True, max_length=64, null=True)),
                ('localidade', clinicas.models.UpperCharField(blank=True, max_length=64, null=True)),
                ('uf', clinicas.models.UpperCharField(blank=True, max_length=2, null=True)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('inativa', 'Inativa')], default='ativa', max_length=20)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clínica',
                'verbose_name_plural': 'Clínicas',
                'db_table': 'clinicas',
            },
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', clinicas.models.UpperCharField(max_length=16, unique=True)),
                ('valor', models.FloatField()),
                ('descricao', clinicas.models.UpperCharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'Parâmetro',
                'verbose_name_plural': 'Parâmetros',
                'db_table': 'parametros',
            },
        ),
    ]
