# Generated by Django 5.2.8 on 2025-11-27 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinicas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinicas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parametro',
            name='clinica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='clinicas.clinica'),
        ),
        migrations.AlterUniqueTogether(
            name='parametro',
            unique_together={('clinica', 'codigo')},
        ),
    ]
