# Generated by Django 5.2.8 on 2025-11-28 11:34

import clinicas.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametro',
            name='codigo',
            field=clinicas.models.UpperCharField(max_length=16, verbose_name='codigo'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='descricao',
            field=clinicas.models.UpperCharField(blank=True, max_length=128, null=True, verbose_name='Descrição'),
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', clinicas.models.UpperCharField(max_length=16)),
                ('descricao', clinicas.models.UpperCharField(blank=True, max_length=128, null=True)),
                ('tipo', models.CharField(choices=[('procedimento', 'Procedimento'), ('custo', 'Custo')], max_length=20)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='clinicas.clinica')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categorias',
                'unique_together': {('clinica', 'codigo')},
            },
        ),
    ]
