# Generated by Django 5.2.8 on 2025-11-29 12:57

import clinicas.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0003_alter_parametro_codigo_alter_parametro_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='codigo',
            field=clinicas.models.UpperCharField(max_length=16, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descricao',
            field=clinicas.models.UpperCharField(blank=True, max_length=128, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('procedimento', 'Procedimento'), ('custo', 'Custo')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='codigo',
            field=clinicas.models.UpperCharField(max_length=16, verbose_name='Código'),
        ),
        migrations.CreateModel(
            name='TipoSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', clinicas.models.UpperCharField(max_length=16, verbose_name='Tipo')),
                ('nome', clinicas.models.UpperCharField(max_length=64, verbose_name='Nome Sala')),
                ('observacao', clinicas.models.UpperCharField(blank=True, max_length=128, null=True, verbose_name='Observação')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('inativa', 'Inativa')], default='ativa', max_length=20, verbose_name='Status')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipossala', to='clinicas.clinica')),
            ],
            options={
                'verbose_name': 'Tipo de Sala',
                'verbose_name_plural': 'Tipos de Sala',
                'db_table': 'tipossala',
                'unique_together': {('clinica', 'tipo')},
            },
        ),
    ]
