# Generated by Django 5.2.8 on 2025-12-01 13:25

import clinicas.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0004_alter_categoria_codigo_alter_categoria_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinica',
            name='bairro',
            field=clinicas.models.UpperCharField(blank=True, max_length=64, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='complemento',
            field=clinicas.models.UpperCharField(blank=True, max_length=32, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='localidade',
            field=clinicas.models.UpperCharField(blank=True, max_length=64, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='logradouro',
            field=clinicas.models.UpperCharField(blank=True, max_length=64, null=True, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='nome',
            field=clinicas.models.UpperCharField(max_length=64, unique=True, verbose_name='Clínica'),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='status',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('inativa', 'Inativa')], default='ativa', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='uf',
            field=clinicas.models.UpperCharField(blank=True, max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', clinicas.models.UpperCharField(max_length=16, verbose_name='Codigo')),
                ('descricao', clinicas.models.UpperCharField(max_length=128, verbose_name='descricao')),
                ('fabricante', clinicas.models.UpperCharField(blank=True, max_length=128, null=True, verbose_name='Fabricante')),
                ('marca', clinicas.models.UpperCharField(blank=True, max_length=64, null=True, verbose_name='Marca')),
                ('dta_aquisicao', models.DateTimeField(blank=True, null=True, verbose_name='Data Aquisição')),
                ('vlr_aquisicao', models.FloatField(blank=True, null=True, verbose_name='Valor Aquisição')),
                ('custo_dia', models.FloatField(blank=True, null=True, verbose_name='Custo Dia')),
                ('custo_mes', models.FloatField(blank=True, null=True, verbose_name='Custo Mes')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=20, verbose_name='Status')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamento', to='clinicas.clinica')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'db_table': 'equipamento',
                'unique_together': {('clinica', 'codigo')},
            },
        ),
    ]
