# Generated by Django 5.2.8 on 2025-12-01 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0005_alter_clinica_bairro_alter_clinica_cep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, verbose_name='Número/Nome da Sala')),
                ('descricao', models.CharField(blank=True, max_length=100, verbose_name='Descrição')),
                ('cor', models.CharField(default='#007bff', help_text='Cor em formato HEX (ex: #ff0000 para vermelho)', max_length=7, verbose_name='Cor no Agendamento')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa?')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='clinicas.clinica')),
                ('equipamentos', models.ManyToManyField(blank=True, help_text='Selecione os equipamentos que ficam nesta sala', related_name='salas', to='clinicas.equipamento')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['numero'],
                'unique_together': {('clinica', 'numero')},
            },
        ),
    ]
