# Generated by Django 5.2.8 on 2025-12-01 17:52

import clinicas.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0006_sala'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sala',
            options={},
        ),
        migrations.RemoveField(
            model_name='sala',
            name='ativa',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='descricao',
        ),
        migrations.AddField(
            model_name='sala',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Sala'),
        ),
        migrations.AddField(
            model_name='sala',
            name='status',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('inativa', 'Inativa')], default='ativo', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='sala',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='clinicas.tiposala'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='cor',
            field=models.CharField(default='#007bff', max_length=7, verbose_name='Cor no Agendamento'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='equipamentos',
            field=models.ManyToManyField(blank=True, related_name='salas_equipamentos', to='clinicas.equipamento'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='numero',
            field=clinicas.models.UpperCharField(max_length=20, verbose_name='Número Sala'),
        ),
        migrations.CreateModel(
            name='CustoFixoSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_item', clinicas.models.UpperCharField(max_length=64)),
                ('valor_mensal', models.FloatField()),
                ('mes_referencia', models.PositiveSmallIntegerField()),
                ('ano_referencia', models.PositiveSmallIntegerField()),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custos_fixos_salas', to='clinicas.clinica')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custos_fixos', to='clinicas.sala')),
            ],
            options={
                'unique_together': {('sala', 'nome_item', 'mes_referencia', 'ano_referencia')},
            },
        ),
        migrations.CreateModel(
            name='CustoVariavelSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_item', clinicas.models.UpperCharField(max_length=64)),
                ('valor_mensal', models.FloatField()),
                ('mes_referencia', models.PositiveSmallIntegerField()),
                ('ano_referencia', models.PositiveSmallIntegerField()),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custos_variaveis_salas', to='clinicas.clinica')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custos_variaveis', to='clinicas.sala')),
            ],
            options={
                'unique_together': {('sala', 'nome_item', 'mes_referencia', 'ano_referencia')},
            },
        ),
    ]
