# Generated by Django 5.2.8 on 2025-12-01 19:31

import clinicas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0007_alter_sala_options_remove_sala_ativa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametro',
            name='valor',
            field=models.CharField(max_length=32, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='cor',
            field=clinicas.models.UpperCharField(default='#007bff', max_length=7, verbose_name='Cor no Agendamento'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='nome',
            field=clinicas.models.UpperCharField(blank=True, max_length=100, null=True, verbose_name='Nome Sala'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='numero',
            field=clinicas.models.UpperCharField(max_length=20, verbose_name='Nro Sala'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='status',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('inativa', 'Inativa')], default='ativa', max_length=20, verbose_name='Status'),
        ),
    ]
