# Generated by Django 5.2.8 on 2025-12-01 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0008_alter_parametro_valor_alter_sala_cor_alter_sala_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custofixosala',
            name='clinica',
        ),
        migrations.RemoveField(
            model_name='custovariavelsala',
            name='clinica',
        ),
    ]
