# Generated by Django 5.2.8 on 2025-12-03 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0009_remove_custofixosala_clinica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custofixosala',
            name='ano_referencia',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='custovariavelsala',
            name='ano_referencia',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
