# Generated by Django 5.2.8 on 2025-12-03 21:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0010_alter_custofixosala_ano_referencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Informe o Nome do Convênio. Obrigatório!', max_length=128, verbose_name='Nome')),
                ('descricao', models.CharField(blank=True, help_text='Informe a Descrição do Convênio. Opcional!', max_length=128, null=True, verbose_name='Descrição')),
                ('fator_reajuste', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='Informe o Fator de Reajuste. Obrigatório!', max_digits=5, verbose_name='Fator de Reajuste')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convenios', to='clinicas.clinica', verbose_name='Clínica')),
            ],
            options={
                'verbose_name': 'Convênio',
                'verbose_name_plural': 'Convênios',
                'unique_together': {('clinica', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='Novo', help_text='Informe o Código do Procedimento. Obrigatório!', max_length=20, unique=True, verbose_name='Código')),
                ('nome', models.CharField(help_text='Informe o Nome do Procedimento. Obrigatório!', max_length=200, verbose_name='Nome do Procedimento')),
                ('descricao', models.CharField(blank=True, help_text='Informe a Descrição do Procedimento. Opcional!', max_length=256, null=True, verbose_name='Descrição')),
                ('tempo_estimado', models.PositiveIntegerField(blank=True, help_text='Tempo em minutos', null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(default='1', help_text='Escolha a Categoria do Procedimento. Obrigatório!', on_delete=django.db.models.deletion.PROTECT, related_name='procedimentos', to='clinicas.categoria', verbose_name='Categoria')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimentos', to='clinicas.clinica', verbose_name='Clínica')),
            ],
            options={
                'verbose_name': 'Procedimento',
                'verbose_name_plural': 'Procedimentos',
                'ordering': ['nome'],
                'unique_together': {('clinica', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='ItemCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('unidade_medida', models.CharField(blank=True, max_length=20, null=True)),
                ('custo_unitario', models.DecimalField(decimal_places=4, help_text='Valor fixo OU será Sobrescrito', max_digits=12)),
                ('categoria_custo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_custo', to='clinicas.categoria')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_custo', to='clinicas.clinica', verbose_name='Clínica')),
                ('referencia_parametro', models.ForeignKey(blank=True, help_text='Se preenchido, ignora custo_unitario e usa o valor atual do parâmetro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_custo_referencia', to='clinicas.parametro')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_custo', to='clinicas.procedimento')),
            ],
        ),
        migrations.CreateModel(
            name='TabelaPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custo_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('margem_desejada', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('preco_base', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('taxas_adicionais', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('preco_venda', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('margem_efetiva', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('status_margem', models.CharField(default='OK', editable=False, max_length=20)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabelas_preco', to='clinicas.clinica', verbose_name='Clínica')),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tabelas_preco', to='clinicas.convenio')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tabelas_preco', to='clinicas.procedimento')),
            ],
            options={
                'verbose_name': 'Tabela de Preço',
                'verbose_name_plural': 'Tabelas de Preço',
                'unique_together': {('clinica', 'procedimento', 'convenio')},
            },
        ),
        migrations.CreateModel(
            name='HistoricoPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custo_total_anterior', models.DecimalField(decimal_places=2, max_digits=12)),
                ('preco_venda_anterior', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('motivo_alteracao', models.TextField(blank=True, null=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='clinicas.clinica', verbose_name='Clínica')),
                ('tabela_preco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='clinicas.tabelapreco')),
            ],
            options={
                'verbose_name': 'Histórico de Preço',
                'verbose_name_plural': 'Históricos de Preço',
                'ordering': ['-data_alteracao'],
            },
        ),
    ]
