# Generated by Django 5.2.8 on 2025-12-03 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0013_alter_perfilusuario_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='clinica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfis_usuarios', to='clinicas.clinica', verbose_name='Clínica'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_clinica', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
