# Generated by Django 5.2.8 on 2025-12-03 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0014_alter_perfilusuario_clinica_alter_perfilusuario_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='clinica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicas.clinica'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
