# Generated by Django 5.2.8 on 2025-12-05 21:42

import clinicas.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0016_alter_perfilusuario_clinica_alter_perfilusuario_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='nome',
            field=clinicas.models.UpperCharField(blank=True, max_length=64, null=True, verbose_name='Nome Sala'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='numero',
            field=clinicas.models.UpperCharField(max_length=16, verbose_name='Nro Sala'),
        ),
    ]
