# Generated by Django 5.2.8 on 2025-12-07 12:57

import clinicas.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0017_alter_sala_nome_alter_sala_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='responsavel',
            field=clinicas.models.UpperCharField(blank=True, max_length=64, null=True, verbose_name='Responsável'),
        ),
    ]
