# Generated by Django 5.2.8 on 2025-12-09 11:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0018_clinica_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='zap',
            field=models.CharField(blank=True, null=True, verbose_name='Whatszap'),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data Atualização'),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data Criação'),
        ),
    ]
