# Generated by Django 5.2.8 on 2025-12-09 14:44

import clinicas.models
import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0019_clinica_email_clinica_zap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenio',
            name='descricao',
            field=clinicas.models.UpperCharField(blank=True, help_text='Informe a Descrição do Convênio. Opcional!', max_length=128, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='convenio',
            name='nome',
            field=clinicas.models.UpperCharField(help_text='Informe o Nome do Convênio. Obrigatório!', max_length=128, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='itemcusto',
            name='nome',
            field=clinicas.models.UpperCharField(max_length=100, verbose_name='Nome Ítem'),
        ),
        migrations.AlterField(
            model_name='itemcusto',
            name='quantidade',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Qtde Ítem'),
        ),
        migrations.AlterField(
            model_name='itemcusto',
            name='unidade_medida',
            field=clinicas.models.UpperCharField(blank=True, max_length=20, null=True, verbose_name='Unid Medida'),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='codigo',
            field=clinicas.models.UpperCharField(default='Novo', help_text='Informe o Código do Procedimento. Obrigatório!', max_length=20, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data Atualização'),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data Criação'),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='descricao',
            field=clinicas.models.UpperCharField(blank=True, help_text='Informe a Descrição do Procedimento. Opcional!', max_length=256, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='nome',
            field=clinicas.models.UpperCharField(help_text='Informe o Nome do Procedimento. Obrigatório!', max_length=200, verbose_name='Nome do Procedimento'),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='tempo_estimado',
            field=models.PositiveIntegerField(blank=True, help_text='Tempo em minutos!', null=True),
        ),
    ]
