# Generated by Django 5.2.8 on 2025-12-09 17:31

import clinicas.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0020_alter_convenio_descricao_alter_convenio_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', clinicas.models.UpperCharField(help_text='Informe o Tipo do Profissional. Obrigatório!', max_length=64, verbose_name='Tipo de Pessoa')),
                ('especialidade', clinicas.models.UpperCharField(blank=True, help_text='Informe a Especialidade do Profissional. Opciona!', max_length=64, null=True, verbose_name='Especialidade')),
                ('tipo', models.CharField(choices=[('saude', 'Saúde'), ('terceiro', 'Terceirizado'), ('adm', 'Administrativo')], default='saude', help_text='Escolha a Função do Profissional. Default Saúde!', max_length=20, verbose_name='Tipo')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipospessoa', to='clinicas.clinica')),
            ],
            options={
                'verbose_name': 'Tipos de Pessoa',
                'verbose_name_plural': 'Tipos de Pessoa',
                'unique_together': {('clinica', 'pessoa')},
            },
        ),
    ]
